### PR TITLE
Support for Kitty terminal graphics

### PR DESCRIPTION
**Pull request by AnonymouX47**
Resolving #40 and #23
- Implements support for the Kitty terminal graphics protocol in the library, CLI and TUI.
- Adds `KittyImage` class.
- Adds `kitty` render style choice for the `--style` CL option.
- Introduces support for multiple render methods per render style.
- Adds `BaseImage.set_render_method()`.

### CODE REVIEW

**Comment by AnonymouX47** [comment]
@leo-arch @paw-lu

Finally! Here comes the first one :smiley:

**Comment by AnonymouX47** [comment]
The library and CLI seem to be quite alright now (all existing features apply by default) but I'm still dealing with clearing images in the TUI.

**Comment by leo-arch** [comment]
Looks great!

**Comment by AnonymouX47** [comment]
Everything seems to be working now. Though, not as good as I want it to be.

Anyways, I feel it's okay for an initial state.
Updates will come along the way (already got some partial ones stashed :smiley:)... after all, It's not like everything will be implemented in one PR 😆.

Just tests for the rendering left to do in this PR.

**Pull request merged**
